apiVersion: v1
kind: ConfigMap
metadata:
  name: odoo-config
  labels:
    app: odoo
data:
  odoo.conf: |
    [options]
    addons_path = /mnt/extra-addons
    admin_passwd = ${ADMIN_PASSWORD}
    csv_internal_sep = ,
    data_dir = /var/lib/odoo
    db_host = postgresql
    db_maxconn = 64
    db_name = ${POSTGRES_DB}
    db_password = ${POSTGRES_PASSWORD}
    db_port = 5432
    db_sslmode = prefer
    db_template = template0
    db_user = ${POSTGRES_USER}
    email_from = odoo@example.com
    http_port = 8069
    list_db = True
    log_level = info
    proxy_mode = True
    smtp_password = False
    smtp_port = 25
    smtp_server = smtp
    smtp_ssl = False
    smtp_user = False
    without_demo = True
    workers = 4
