apiVersion: v1
kind: Service
metadata:
  name: odoo
  namespace: odoo
  labels:
    app: odoo
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8069
    protocol: TCP
    name: http
  selector:
    app: odoo
