apiVersion: v1
kind: Service
metadata:
  name: odoo
  namespace: odoo
  labels:
    app: odoo
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8069
    nodePort: 30080
    protocol: TCP
  - name: longpolling
    port: 8072
    targetPort: 8072
    nodePort: 30081
    protocol: TCP
  selector:
    app: odoo
