apiVersion: v1
kind: Secret
metadata:
  name: postgresql-credentials
type: Opaque
data:
  POSTGRES_DB: b2Rvbw==  # odoo
  POSTGRES_USER: b2Rvbw==  # odoo
  POSTGRES_PASSWORD: b2Rvbw==  # odoo
  ADMIN_PASSWORD: YWRtaW4=  # admin
