apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - secret.yaml

# Configuration pour les secrets
generatorOptions:
  disableNameSuffixHash: true
