apiVersion: v1
kind: Secret
metadata:
  name: odoo-secrets
type: Opaque
data:
  # Mot de passe administrateur Odoo (admin)
  admin-password: YWRtaW4=  # admin en base64
  # Clé secrète pour le chiffrement des données sensibles
  secret-key: $(echo -n $(openssl rand -base64 32) | base64 -w0)
  # Identifiants de base de données
  db-host: cG9zdGdyZXNxbA==  # postgresql en base64
  db-port: NTQzMg==          # 5432 en base64
  db-user: b2Rvbw==          # odoo en base64
  db-password: b2Rvbw==      # odoo en base64
  db-name: b2Rvbw==          # odoo en base64
  # Configuration SMTP (exemple avec des valeurs vides)
  smtp-host: ""
  smtp-port: ""
  smtp-user: ""
  smtp-password: ""
  smtp-ssl: ""
  smtp-user: ""
