# odoo/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: odoo-config
  namespace: odoo
data:
  odoo.conf: |
    [options]
    admin_passwd = ${ADMIN_PASSWORD}
    db_host = postgres
    db_port = 5432
    db_user = odoo
    db_password = ${DB_PASSWORD}
    db_name = postgres
    addons_path = /mnt/extra-addons
    data_dir = /var/lib/odoo
    proxy_mode = True
    workers = 2
    max_cron_threads = 1
    limit_memory_hard = 1677721600
    limit_memory_soft = 629145600
    limit_time_cpu = 600
    limit_time_real = 1200
