apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - cert-manager.yaml
  - cluster-issuer.yaml

# Configuration commune pour Cert-Manager
labels:
  app.kubernetes.io/name: cert-manager
  app.kubernetes.io/instance: cert-manager
  app.kubernetes.io/component: cert-manager
