apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Installation de Cert-Manager via son manifeste officiel
  - https://github.com/cert-manager/cert-manager/releases/download/v1.13.1/cert-manager.yaml

# Personnalisation des ressources
patches:
  - target:
      kind: Deployment
      name: cert-manager
      namespace: cert-manager
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --default-issuer-kind=ClusterIssuer
        value: --default-issuer-group=cert-manager.io
  - target:
      kind: Deployment
      name: cert-manager-webhook
      namespace: cert-manager
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --default-issuer-kind=ClusterIssuer
        value: --default-issuer-group=cert-manager.io
