apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secrets
type: Opaque
data:
  postgres-password: b2Rvbw==  # odoo en base64
  postgres-user: b2Rvbw==      # odoo en base64
  postgres-db: b2Rvbw==        # odoo en base64
