apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base

# Configuration pour ArgoCD
commonAnnotations:
  argocd.argoproj.io/sync-options: Prune=false
  argocd.argoproj.io/sync-wave: "0"

# Variables de configuration
configMapGenerator:
- name: odoo-config
  files:
    - config/odoo.conf

secretGenerator:
- name: odoo-secrets
  literals:
    - POSTGRES_PASSWORD=odoo
    - ADMIN_PASSWORD=admin

# Configuration des ressources à déployer
resources:
  - base/namespace.yaml
  - base/postgresql
  - base/odoo
